Add iota snap
ubuntu/snappy-playpen pull request #76
Opened 2016-06-17 15:19 UTC by mariogrip

This requires this patch of snapcraft to work: https://github.com/ubuntu-core/snapcraft/pull/579

2016-06-21 10:37 UTC, dholbach commented
*[iota/snapcraft.yaml, line 12 \[r1\]](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/76#-KKmXNDoKnE-Efc-2HnC:-KKmXNDpxQMVKisNTChV:-1602625031) ([raw file](https://github.com/ubuntu/snappy-playpen/blob/d67f944f0c801ee04a516eb4575c232d25d8f708/iota/snapcraft.yaml#L12)):*
> ```YAML
> parts:
>   iota:
>     plugin: rust
> ```

We're still blocked here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ubuntu/snappy-playpen/76)*
<!-- Sent from Reviewable.io -->

2016-09-19 11:59 UTC, tachyons commented
Any updates ? rust plugin is already merged to snapcraft

2016-09-19 12:12 UTC, dholbach commented
Thanks for the ping, I restarted the CI run.

2016-09-19 12:17 UTC, dholbach commented on iota/snapcraft.yaml
> +    source-type: git
This line shouldn't be necessary as the URL below ends with `.git`.

2016-09-19 12:18 UTC, dholbach commented on iota/snapcraft.yaml
> +
It'd be good to define `confinement` and `grade` in here.

2016-09-19 12:18 UTC, dholbach commented on iota/snapcraft.yaml
> +        command: iota
Are no `plugs` required? `[home]` maybe?

2016-09-19 12:19 UTC, dholbach requested changes
Some small bits need to be updated.

2016-09-19 12:19 UTC, dholbach commented
The build fails still: https://travis-ci.org/ubuntu/snappy-playpen/builds/138389626

2016-09-19 12:21 UTC, dholbach commented on README.md
> +| :white_check_mark:  | `iota    `         |                           |
Missing ` and it'd be good to add a few words about which plugins it uses, etc.

2016-09-19 12:36 UTC, tachyons commented
Seems like build failure is from atom package , node version is to be updated

2020-01-20 14:12 UTC, closed without merging